// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHH1gq8PG6TECwfvv7tKOt2Ce3mmQOtXE',
    appId: '1:941472432447:web:de3a33b1b6dd2a2959538a',
    messagingSenderId: '941472432447',
    projectId: 'lala-ba34c',
    authDomain: 'lala-ba34c.firebaseapp.com',
    storageBucket: 'lala-ba34c.firebasestorage.app',
    measurementId: 'G-94DHNX72TH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJlaE0PF9elsWeEw_Rz9MEPIiirbBuh1I',
    appId: '1:941472432447:android:3238c94c864c078f59538a',
    messagingSenderId: '941472432447',
    projectId: 'lala-ba34c',
    storageBucket: 'lala-ba34c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASbckoqoLnw0aXp2VLN1P-WYiq34EPwwo',
    appId: '1:941472432447:ios:ce49d6b0fa42c9a359538a',
    messagingSenderId: '941472432447',
    projectId: 'lala-ba34c',
    storageBucket: 'lala-ba34c.firebasestorage.app',
    iosBundleId: 'com.example.lala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASbckoqoLnw0aXp2VLN1P-WYiq34EPwwo',
    appId: '1:941472432447:ios:ce49d6b0fa42c9a359538a',
    messagingSenderId: '941472432447',
    projectId: 'lala-ba34c',
    storageBucket: 'lala-ba34c.firebasestorage.app',
    iosBundleId: 'com.example.lala',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHH1gq8PG6TECwfvv7tKOt2Ce3mmQOtXE',
    appId: '1:941472432447:web:8877f26c69531b6659538a',
    messagingSenderId: '941472432447',
    projectId: 'lala-ba34c',
    authDomain: 'lala-ba34c.firebaseapp.com',
    storageBucket: 'lala-ba34c.firebasestorage.app',
    measurementId: 'G-MT4D78ENCT',
  );
}
